Sites/CollegeList/config/routes.rb
CollegeList::Application.routes.draw do
  resources :colleges
  resources :users
  resources :sessions
  resources :steps
  
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"

  match "colleges/:id" => "colleges#show", :as => "show_college"

  match "colleges/:id/steps/new" => "steps#new", :as => "new_step"
  match "colleges/:college/steps/:step/edit" => "steps#edit", :as => "edit_step"

  root :to => "sessions#new"

end

Sites/CollegeList/app/models/college.rb
class College < ActiveRecord::Base
  attr_accessible :accepted, :address1, :address2, :city, :complete, :due_date, :name, :state, :student_progress, :student_rank, :tuition, :user_id, :zip, :percent_complete

  belongs_to :users
  has_many :steps

  validates_presence_of :name
  validates_presence_of :due_date
  validates_presence_of :student_rank

end

Sites/CollegeList/app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :college_id, :complete, :duedate, :name

  validates :name, :presence => true, :on => :update
  validates :duedate, :presence => true, :on => :update
end

Sites/CollegeList/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :GPA, :allow_email_notifications, :allow_text, :date_of_birth, :email, :first_name, :last_name, :phone, :sat, :password, :password_confirmation

  has_many :colleges

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_confirmation_of :email
  validates_uniqueness_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name

  def self.authenticate(email, password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  	 	user
  	else
  		nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

Sites/CollegeList/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

Sites/CollegeList/app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
	def new
		@college = College.new
	end

	def create
		@college = College.new(params[:college])
		@college.user_id = session[:user_id]
		if @college.save
			redirect_to user_path(@college.user_id), :notice => "Your college was saved!"
		else
			render "new"
		end
	end

	def show
		@college = College.find_by_id(params[:id])
		@steps = Step.order(:duedate).where("college_id = ?", params[:id])
		calc_percent_complete
	end

	def calc_percent_complete
        completed_steps = 0

		if @steps.length > 0
			@steps.each do|step|
				if step.complete
					completed_steps += 1
				end
			end
			if	@college.update_attribute(:percent_complete, (completed_steps.to_f / @steps.length.to_f  * 100).round)
				puts "updated percent complete"
			else
				puts "error"
			end
		else
			@college.update_attribute(:percent_complete, 0)
		end
	end
end

Sites/CollegeList/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.authenticate(params[:email], params[:password])
		if user
			session[:user_id] = user.id
			redirect_to "/users/show"
		else
			flash[:error] = "Invalid username or password!"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "Logged out!"
	end
end

Sites/CollegeList/app/controllers/steps_controller.rb
class StepsController < ApplicationController
	def new
		@step = Step.new
		@college = College.find_by_id(params[:id])
	end

	def create
		@college = College.find_by_id(params[:id])
		@step = Step.new(params[:step])

		if @step.save
			redirect_to college_path(:id => @step.college_id), :notice => "Created step!"
		else
			render "new"
		end
	end
	def update
		step = Step.find_by_id(params[:id])
      	if step.update_attributes(params[:step])
      		redirect_to college_path(:id => step.college_id), :flash => {:success => "Step was saved!"}
		else
			Rails.logger.info(@step.errors.messages.inspect)
			redirect_to college_path(:id => @step.college_id), :flash => {:error =>  "Step couldn't be saved!"}
		end
	end 

end	

Sites/CollegeList/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			session[:user_id] = @user.id
			redirect_to "/users/show", :notice => "Signed up!"
		else
			render "new"
		end
	end

	def show
		@user = User.find(session[:user_id])
    	@colleges = College.where("user_id = ?",@user.id)
	end
end

Sites/CollegeList/app/helpers/application_helper.rb
module ApplicationHelper
end

Sites/CollegeList/app/helpers/sessions_helper.rb
module SessionsHelper
end

Sites/CollegeList/app/helpers/users_helper.rb
module UsersHelper
end

Sites/CollegeList/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollegeList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

</head>
<body>
	<nav>
		<% if current_user %>
			<ul>
				<li><%= link_to "Log out", log_out_path %></li>
				<li><%= link_to "My colleges", user_path(session[:user_id]) %></li>
				<li><a href="#">Logged in as <%= current_user.first_name %>.</a></li>
		<% else %>
				<%= link_to "Sign up", sign_up_path %>
				or 
				<%= link_to "Log in", log_in_path %>
			</ul>
		<% end %>
	</nav>
	<div class = "message">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :class => "flash #{name}" %>
		<% end %>
	</div>
<div id="content">
	<%= yield %>
	<!-- For debuggin params <%= params.inspect %> -->
</div>

</body>
</html>

Sites/CollegeList/app/views/users/_form.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class ="error_messages">
	<h2> Form is invalid</h2>
	<ul>
		<% for message in @user.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<p>
	<%= f.label :first_name %><br />
	<%= f.text_field :first_name %>
</p>

<p>
	<%= f.label :last_name %><br />
	<%= f.text_field :last_name %>
</p>

<p>
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</p>

<p>
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</p>

<p>
	<%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %>
</p>
<p class = "button"><%= f.submit %></p>
<% end %>

Sites/CollegeList/app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', 'show_colleges' %>

Sites/CollegeList/app/views/users/show.html.erb
<div class ="college-list clearfix">
  <div class = "college-header">
    <div>
        <h4>My Colleges</h4>
    </div>
    <div class = "add-college">
          <%= link_to "Add new college", new_college_path %>
    </div>
  </div>
  <% if @colleges.length > 0 %>
    <% @colleges.each do |college| %>
    <div class ="college">
      <div>
        <%= college.student_rank %>
      </div>
      
      <div>
        <%= link_to college.name, college_path(college.id) %>
      </div>

      <div>
        <b>Due date:</b>
        <%= college.due_date %>
      </div>
      <div class ="ui-progress-bar ui-container transition" id="progress_bar">
          <div class="ui-progress" style="width: <%= college.percent_complete %>%;">
              <span class="ui-label" style="display: none;">Completed</span>
          </div>
      </div>
      <div>
        <b>Complete?</b>
        <%= college.complete %>
      </div>
       
      <div>
        <b>Accepted?</b>
        <%= check_box_tag :complete %>
      </div>
    </div>
  <% end %>
</div>

<% else %>
<p>You don't have any colleges yet, would you like to add one? <%= link_to "create college", new_college_path %></p>
  <% end %>