Sites/College_List_Test/config/routes.rb
CollegeListTest::Application.routes.draw do
  resources :steps

  resources :colleges

  resources :users

  root :to => 'colleges#index'

end

Sites/College_List_Test/app/models/college.rb
class College < ActiveRecord::Base
  attr_accessible :accepted, :address1, :address2, :city, :complete, :duedate, :name, :state, :num_steps, :zip, :steps, :user_id, :student_rank

  belongs_to :users
  has_many :steps

  validates :address1, :city, :duedate, :name, :state, :zip, :student_rank, :presence => true

end

Sites/College_List_Test/app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :complete, :due_date, :name, :step_type_id

  belongs_to :colleges

  validates :due_date, :name, :presence => true
end

Sites/College_List_Test/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :allow_email, :allow_text, :birthdate, :email, :first_name, :gpa, :last_name, :password, :phone, :sat

  has_many :colleges

  validates :email, :first_name, :last_name, :password, :phone, :presence => true
 
 def order_colleges_by_rank
 	colleges_ranked = []
  colleges = College.where("user_id = ?", :user_id)
  colleges.each do |college|
  	puts colleges.name
  	colleges_ranked = push(colleges.find_by_student_rank(college))
  end
    puts colleges_ranked
 end
end

Sites/College_List_Test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

Sites/College_List_Test/app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colleges }
    end
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
    @college = College.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/new
  # GET /colleges/new.json
  def new
    @college = College.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @college }
    end
  end

  # GET /colleges/1/edit
  def edit
    @college = College.find(params[:id])
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(params[:college])

    respond_to do |format|
      if @college.save
        flash[:sucess] = "Welcome to college list!"
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render json: @college, status: :created, location: @college }
      else
        format.html { render action: "new" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colleges/1
  # PUT /colleges/1.json
  def update
    @college = College.find(params[:id])

    respond_to do |format|
      if @college.update_attributes(params[:college])
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college = College.find(params[:id])
    @college.destroy

    respond_to do |format|
      format.html { redirect_to colleges_url }
      format.json { head :no_content }
    end
  end
end

Sites/College_List_Test/app/controllers/steps_controller.rb
class StepsController < ApplicationController
  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
    @step = Step.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/1/edit
  def edit
    @step = Step.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(params[:step])

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
    @step = Step.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to steps_url }
      format.json { head :no_content }
    end
  end
end

Sites/College_List_Test/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @colleges = College.where("user_id", @user.id).order("student_rank")


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

Sites/College_List_Test/app/helpers/colleges_helper.rb
module CollegesHelper
end

Sites/College_List_Test/app/helpers/steps_helper.rb
module StepsHelper
end

Sites/College_List_Test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CollegeListTest" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" <%= link_to 'colleges', '/colleges' %></a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "colleges", "/colleges"  %></li>
              <li><%= link_to "account", "/users"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container bootstrap-margin">
        <div class="row">
          <div class="span10">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

Sites/College_List_Test/app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :step_type_id %><br />
    <%= f.number_field :step_type_id %>
  </div>
  <div class="field">
    <%= f.label :complete %><br />
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Sites/College_List_Test/app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

Sites/College_List_Test/app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Due date</th>
    <th>Step type</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.name %></td>
    <td><%= step.due_date %></td>
    <td><%= step.step_type_id %></td>
    <td><%= step.complete %></td>
    <td><%= link_to 'Show', step %></td>
    <td><%= link_to 'Edit', edit_step_path(step) %></td>
    <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_step_path %>

Sites/College_List_Test/app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

Sites/College_List_Test/app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @step.name %>
</p>

<p>
  <b>Due date:</b>
  <%= @step.due_date %>
</p>

<p>
  <b>Step type:</b>
  <%= @step.step_type_id %>
</p>

<p>
  <b>Complete:</b>
  <%= @step.complete %>
</p>


<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>